# Generated by Django 5.1.2 on 2024-12-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
