# Generated by Django 5.1.2 on 2024-11-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images')),
                ('job_title', models.CharField(max_length=150)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time')], max_length=50)),
                ('location', models.CharField(max_length=150)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('job_category', models.CharField(choices=[('Healthcare', 'Healthcare'), ('IT', 'IT'), ('Finance', 'Finance'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
