# Generated by Django 5.1.2 on 2024-12-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
