# Generated by Django 5.1.2 on 2024-12-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
