# Generated by Django 5.1.2 on 2025-01-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='employer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
