# Generated by Django 5.1.2 on 2025-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_applications_employer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='job',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applications',
            name='seeker',
            field=models.IntegerField(),
        ),
    ]
