# Generated by Django 5.1.2 on 2025-01-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_alter_applications_job_alter_applications_seeker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='job',
            new_name='job_id',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='seeker',
            new_name='seeker_id',
        ),
    ]
